version: '3.9'

services:
  web:
    build: .
    command: bash -c "python manage.py migrate --settings=core.settings.prod
             && python manage.py collectstatic --settings=core.settings.prod
             && gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/usr/src/VinylCollector/
      - static_volume:/home/VinylCollector/web/static
      - media_volume:/home/VinylCollector/web/media
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:13.3
    restart: always
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=vinylcollector
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345678
    ports:
      - "5432:5432"
  nginx:
    build: ./nginx
    restart: always
    volumes:
      - static_volume:/home/VinylCollector/web/static
      - media_volume:/home/VinylCollector/web/media
      - certbot:/var/www/certbot/:ro
      - certbot:/etc/nginx/ssl/:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
  certbot:
    image: certbot/certbot:latest
    volumes:
      - certbot:/var/www/certbot/:rw
      - certbot:/etc/letsencrypt/:rw

volumes:
  postgres_volume:
  static_volume:
  media_volume:
  certbot: