version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000 --settings=core.settings.prod
    volumes:
      - .:/usr/src/VinylCollector/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:13.3
    restart: always
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=vinylcollector
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345678
    ports:
      - "5432:5432"

volumes:
  postgres_volume: