# Generated by Django 4.1.3 on 2023-04-12 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vinyl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release', models.CharField(blank=True, max_length=24, null=True, verbose_name='Release Discogs')),
                ('artist', models.CharField(max_length=80, verbose_name='Artist')),
                ('album', models.CharField(max_length=80, verbose_name='Album')),
                ('genres', models.CharField(blank=True, max_length=80, null=True, verbose_name='Genres')),
                ('styles', models.CharField(blank=True, max_length=80, null=True, verbose_name='Styles')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('formats', models.CharField(blank=True, max_length=24, null=True, verbose_name='Formats')),
                ('qty', models.CharField(blank=True, max_length=8, null=True, verbose_name='Qty')),
                ('manufacture_region', models.CharField(blank=True, max_length=80, null=True, verbose_name='Manufacture region')),
                ('label', models.CharField(blank=True, max_length=80, null=True, verbose_name='Label')),
                ('catalogue_number', models.CharField(blank=True, max_length=80, null=True, verbose_name='Catalogue number')),
                ('year', models.CharField(blank=True, max_length=80, null=True, verbose_name='Year')),
                ('average_rating', models.CharField(blank=True, max_length=80, null=True, verbose_name='Average rating')),
                ('owners_number', models.DecimalField(blank=True, decimal_places=0, max_digits=80, null=True, verbose_name='Owners')),
                ('sell_number', models.DecimalField(blank=True, decimal_places=0, max_digits=80, null=True, verbose_name='Sell')),
                ('lowest_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Lowest price, USD')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image')),
                ('image_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Image URL')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Added to collection')),
                ('user_rating', models.CharField(blank=True, max_length=2, null=True, verbose_name='User rating')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
