# Generated by Django 4.1.3 on 2023-04-05 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vinyl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release', models.CharField(blank=True, max_length=24, null=True, verbose_name='Release Discogs')),
                ('artist', models.CharField(max_length=80, verbose_name='Artist')),
                ('album', models.CharField(max_length=80, verbose_name='Album')),
                ('genres', models.CharField(blank=True, max_length=80, null=True, verbose_name='Genres')),
                ('styles', models.CharField(blank=True, max_length=80, null=True, verbose_name='Styles')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('formats', models.CharField(blank=True, max_length=24, null=True, verbose_name='Formats')),
                ('qty', models.CharField(blank=True, max_length=8, null=True, verbose_name='Qty')),
                ('manufacture_region', models.CharField(max_length=80, verbose_name='Manufacture region')),
                ('label', models.CharField(max_length=80, verbose_name='Label')),
                ('catalogue_number', models.CharField(blank=True, max_length=80, null=True, verbose_name='Catalogue number')),
                ('year', models.CharField(max_length=80, verbose_name='Year')),
                ('average_rating', models.CharField(blank=True, max_length=80, null=True, verbose_name='Average rating')),
                ('owners_number', models.DecimalField(blank=True, decimal_places=0, max_digits=80, null=True, verbose_name='Owners')),
                ('sell_number', models.DecimalField(blank=True, decimal_places=0, max_digits=80, null=True, verbose_name='Sell')),
                ('lowest_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Lowest price, USD')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image')),
                ('image_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Image URL')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Added to collection')),
                ('user_rating', models.CharField(blank=True, max_length=2, null=True, verbose_name='User rating')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
