# Generated by Django 4.1.3 on 2023-03-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinylcollector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinyl',
            name='catalogue_number',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Catalogue number'),
        ),
    ]
