# Generated by Django 4.1.3 on 2023-03-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinylcollector', '0002_alter_vinyl_catalogue_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinyl',
            name='user_rating',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='User rating'),
        ),
    ]
