# Generated by Django 4.1.3 on 2023-04-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinylcollector', '0002_alter_vinyl_manufacture_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinyl',
            name='label',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='vinyl',
            name='year',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Year'),
        ),
    ]
