# Generated by Django 4.1.3 on 2022-12-20 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinylcollector', '0003_vinyl_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vinyl',
            old_name='owners',
            new_name='owners_number',
        ),
        migrations.RenameField(
            model_name='vinyl',
            old_name='sell',
            new_name='sell_number',
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
