# Generated by Django 4.1.3 on 2022-12-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinylcollector', '0005_alter_vinyl_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinyl',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='vinyl',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image'),
        ),
    ]
