# Generated by Django 4.1.3 on 2022-12-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinylcollector', '0006_vinyl_image_url_alter_vinyl_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinyl',
            name='average_rating',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Average rating'),
        ),
        migrations.AlterField(
            model_name='vinyl',
            name='formats',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='Formats'),
        ),
        migrations.AlterField(
            model_name='vinyl',
            name='genres',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Genres'),
        ),
        migrations.AlterField(
            model_name='vinyl',
            name='lowest_price',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Lowest price, USD'),
        ),
        migrations.AlterField(
            model_name='vinyl',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='vinyl',
            name='owners_number',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Owners'),
        ),
        migrations.AlterField(
            model_name='vinyl',
            name='qty',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Qty'),
        ),
        migrations.AlterField(
            model_name='vinyl',
            name='release',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='Release Discogs'),
        ),
        migrations.AlterField(
            model_name='vinyl',
            name='sell_number',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Sell'),
        ),
        migrations.AlterField(
            model_name='vinyl',
            name='styles',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Styles'),
        ),
    ]
