# Generated by Django 4.1.3 on 2023-01-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinylcollector', '0007_alter_vinyl_average_rating_alter_vinyl_formats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinyl',
            name='lowest_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Lowest price, USD'),
        ),
        migrations.AlterField(
            model_name='vinyl',
            name='owners_number',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=80, null=True, verbose_name='Owners'),
        ),
        migrations.AlterField(
            model_name='vinyl',
            name='sell_number',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=80, null=True, verbose_name='Sell'),
        ),
    ]
